version: 0.0.1
 
# Change default server ports
server:
  applicationConnectors: 
  - type: http
    port: 9095
  adminConnectors:
  - type: http
    port: 9096

swagger:
  resourcePackage: com.kv.api
